
########################################################################################################################
# 스프링 기본설정
########################################################################################################################
spring:
  banner:
    # 배너설정 : 서버 뜰때 예쁘게 예쁘게
    location: classpath:logo.txt

#  security:
#    user:
#      name: dm7
#      password: dm7

  application:
    name: dm7

---

########################################################################################################################
# 서버 정보 설정 (일단 기본 8080 포트로)
########################################################################################################################
server:
  port: ${PORT:8080}

---