
########################################################################################################################
# 스프링 기본설정
########################################################################################################################
spring:
  banner:
    # 배너설정 : 서버 뜰때 예쁘게 예쁘게
    location: classpath:logo.txt

#  security:
#    user:
#      name: dm7
#      password: dm7

  application:
    name: dm7
      
---

########################################################################################################################
# 서버 정보 설정 (일단 기본 8080 포트로)
########################################################################################################################
server:
  port: ${PORT:8080}

---

########################################################################################################################
# JPA
########################################################################################################################
spring:
  jpa:
    hibernate:
      ddl-auto: update    # create, update, create-drop, none 등의 옵션이 있습니다.
                          # create: 기존테이블 삭제 후 다시 생성
                          # update: 변경된 부분만 반영
                          # create-drop: create와 같으나 종료 시점에 테이블 DROP
                          # none: 사용하지 않음
    generate-ddl: false   # DDl 생성 시 데이터베이스 고유의 기능 사용여부
    show-sql: true        # 실행되는 쿼리문 보여주기 여부
    database: mysql       # 사용되는 데이터베이스(MariaDB는 없기 때문에 mysql로 지정)
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 테이블 생성시 엔진을 InnoDB 로 생성. 설정하지 않으면 myisam로 등록

---

########################################################################################################################
# MYSQL
########################################################################################################################
spring:
  datasource:
    username: sql12248426
    password: eULaepVdzK
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://sql12.freemysqlhosting.net:3306/sql12248426?useSSL=false
